import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tech Talk Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={inter.className}>
      <div className="flex justify-center items-center h-screen bg-gray-100">
        <div className="w-1/3 bg-white p-6 rounded shadow">{children}</div>
      </div>
    </div>
  );
}
